title: DnD Fortune Cookie
description: A fortune-cookie generator to have a glimpse at your fate when beginning your DnD session.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
