title: Midnight theme
description: Midnight is a theme for GitHub Pages. heyyy
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
